"""add_rate_limit_columns_to_users

Revision ID: 534eede37346
Revises: 82167bfb9ba6
Create Date: 2026-07-27 22:15:20.047628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534eede37346'
down_revision: Union[str, Sequence[str], None] = '82167bfb9ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_ask_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_ask_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_ask_date')
    op.drop_column('users', 'daily_ask_count')
    # ### end Alembic commands ###
