"""add_tag_to_messages

Revision ID: d24e23db313e
Revises: 534eede37346
Create Date: 2026-07-29 05:47:19.600303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24e23db313e'
down_revision: Union[str, Sequence[str], None] = '534eede37346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tag', sa.String(), nullable=True))
    op.alter_column('users', 'daily_token_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'daily_token_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('messages', 'tag')
    # ### end Alembic commands ###
